test basic {inc=../libstd,inc=..} = basic.myr testmatch.myr;;
test boundaries {inc=../libstd,inc=..} = boundaries.myr testmatch.myr;;
test capture {inc=../libstd,inc=..} = capture.myr testmatch.myr;;
test class {inc=../libstd,inc=..} = class.myr testmatch.myr;;
test failmatch {inc=../libstd,inc=..} = failmatch.myr testmatch.myr;;
test negclass {inc=../libstd,inc=..} = negclass.myr testmatch.myr;;
test unicode {inc=../libstd,inc=..} = unicode.myr testmatch.myr;;
