</$objtype/mkfile
CC=pcc
LD=pcc
CFLAGS=-c -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_C99_SNPRINTF_EXTENSION

LIB=libparse.a
OFILES=bitset.$O \
    dump.$O \
    gram.$O \
    htab.$O \
    infer.$O \
    names.$O \
    node.$O \
    specialize.$O \
    stab.$O \
    tok.$O \
    type.$O \
    use.$O \
    util.$O

HFILES=parse.h ../config.h
CLEANFILES=gram.c gram.h

</sys/src/cmd/mklib

install:V: $LIB
	touch $LIB

uninstall:V:
	echo nothing to uninstall

gram.c gram.h: gram.y
	yacc -d -S gram.y
    mv y.tab.c gram.c
    mv y.tab.h gram.h
