test basic = 
	basic.myr
	testmatch.myr
	lib @/lib/std:std
	lib @/lib/sys:sys
	lib @/lib/regex:regex
;;

test idxmatch = 
	idxmatch.myr
	testmatch.myr
	lib @/lib/std:std
	lib @/lib/sys:sys
	lib @/lib/regex:regex
;;

test boundaries =
	boundaries.myr
	testmatch.myr
	lib @/lib/std:std
	lib @/lib/sys:sys
	lib @/lib/regex:regex
;;
test capture =
	capture.myr
	testmatch.myr
	lib @/lib/std:std
	lib @/lib/sys:sys
	lib @/lib/regex:regex
;;
test class =
	class.myr
	testmatch.myr
	lib @/lib/std:std
	lib @/lib/sys:sys
	lib @/lib/regex:regex
;;
test failmatch =
	failmatch.myr
	testmatch.myr
	lib @/lib/std:std
	lib @/lib/sys:sys
	lib @/lib/regex:regex
;;
test negclass =
	negclass.myr 
	testmatch.myr
	lib @/lib/std:std
	lib @/lib/sys:sys
	lib @/lib/regex:regex
;;
test unicode  =
	unicode.myr
	testmatch.myr
	lib @/lib/std:std
	lib @/lib/sys:sys
	lib @/lib/regex:regex
;;

test search  =
	search.myr
	testmatch.myr
	lib @/lib/std:std
	lib @/lib/sys:sys
	lib @/lib/regex:regex
;;

test subst  =
	subst.myr
	testmatch.myr
	lib @/lib/std:std
	lib @/lib/sys:sys
	lib @/lib/regex:regex
;;
