</$objtype/mkfile
CC=pcc
LD=pcc
CFLAGS=-c -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_C99_SNPRINTF_EXTENSION -I../parse

LIB=libmi.a
OFILES=\
	cfg.$O\
	fold.$O\
        match.$O\
	dfcheck.$O\
	reaching.$O\

HFILES=mi.h ../config.h ../parse/parse.h

</sys/src/cmd/mklib

install:V: $LIB
	touch $LIB

uninstall:V:
	echo $LIB: nothing to uninstall
