</$objtype/mkfile
CC=pcc
LD=pcc
CFLAGS=-c -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_C99_SNPRINTF_EXTENSION -I../parse

LIB=libmi.a
OFILES=\
	cfg.$O\
	fold.$O\
        match.$O\
	df.$O\

HFILES=mi.h ../config.h ../parse/parse.h

</sys/src/cmd/mklib

