INSTBIN=6m
OBJ= \
	blob.o \
	gen.o \
	gengas.o \
	genp9.o \
	isel.o \
	locs.o \
	main.o \
	ra.o \
	peep.o \
	simp.o \
	typeinfo.o \

DEPS=../parse/libparse.a ../mi/libmi.a ../util/libutil.a

include ../config.mk
include ../mk/c.mk
