</$objtype/mkfile
CC=pcc
CFLAGS=-c -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_C99_SNPRINTF_EXTENSION -I../parse -I../opt
LDFLAGS=-L../parse -lparse -L../opt -lopt 

TARG=6m
OFILES=isel.$O \
    locs.$O \
    main.$O \
    ra.$O \
    simp.$O \

LIB=../parse/libparse.a ../opt/libopt.a

</sys/src/cmd/mkone