</$objtype/mkfile

CC=pcc
CFLAGS=-c -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_C99_SNPRINTF_EXTENSION -I../parse -I../mi
LDFLAGS=-L../parse -lparse -L../mi -lmi

TARG=6m
OFILES=\
	gen.$O\
	gengas.$O\
	genp9.$O\
	isel.$O\
	locs.$O\
	main.$O\
	ra.$O\
	simp.$O\
	typeinfo.$O\

LIB=../parse/libparse.a ../mi/libmi.a

HFILES=asm.h ../parse/parse.h ../mi/mi.h ../config.h

BIN=/$objtype/bin
</sys/src/cmd/mkone
