MAN=myr-regex.3 \

include ../config.mk

all:
	
install:
	@echo install -m 644 $(MAN) $(INST_ROOT)/share/man/man1; \
	mkdir -p $(INST_ROOT)/share/man/man1; \
	install -m 644 $(MAN) $(INST_ROOT)/share/man/man1; \

clean:

