</$objtype/mkfile
CC=pcc
CFLAGS=-c -D_POSIX_SOURCE -D_SUSV2_SOURCE -D_C99_SNPRINTF_EXTENSION -I../parse
LDFLAGS=-L../parse -lparse

TARG=myrbuild
OFILES=myrbuild.$O
LIB=../parse/libparse.a

BIN=/$objtype/bin
</sys/src/cmd/mkone
