lib sys =
	sys+freebsd-x64.myr
	sys+linux-x64.myr
	sys+osx-x64.myr
	sys+plan9-x64.myr
	syscall+freebsd-x64.s
	syscall+linux-x64.s
	syscall+osx-x64.s
	syscall+plan9-x64.s
	syserrno+linux.myr
	syserrno+osx.myr
	syserrno+freebsd.myr
	systypes.myr
	ifreq+freebsd.myr
	ifreq+linux.myr
	ifreq+osx.myr
	ifreq+plan9.myr
	ifreq.myr	# dummy file: plan9 doesn't have ifreq
	util+plan9-x64.s
	util+posixy-x64.s
;;

