#!/bin/sh
# This script is generated by genbootstrap.sh
# to regenerate, run "make bootstrap"
pwd=`pwd`
set -x
	$pwd/6/6m -I lib/sys -I lib/std -I lib/bio -I lib/regex -I lib/thread mbld/config.myr
	as -g -o lib/thread/start.o lib/thread/start+osx-x64.s
	as -g -o lib/thread/atomic-impl.o lib/thread/atomic-impl+x64.s
	as -g -o lib/std/getbp.o lib/std/getbp+posixy-x64.s
	$pwd/6/6m -I . -I lib/sys lib/std/option.myr
	as -g -o lib/std/memops-impl.o lib/std/memops-impl+posixy-x64.s
	as -g -o lib/std/sjlj-impl.o lib/std/sjlj-impl+posixy-x64.s
	$pwd/6/6m -I . -I lib/sys lib/std/sjlj.myr
	$pwd/6/6m -I . -I lib/sys lib/std/swap.myr
	$pwd/6/6m -I . -I lib/sys lib/std/slfill.myr
	$pwd/6/6m -I . -I lib/sys lib/std/clear.myr
	$pwd/6/6m -I . -I lib/sys lib/std/result.myr
	as -g -o lib/sys/syscall.o lib/sys/syscall+osx-x64.s
	$pwd/6/6m lib/sys/syserrno+osx.myr
	ar -rcs lib/sys/libsys.a lib/sys/sys.o lib/sys/syserrno.o lib/sys/util.o lib/sys/systypes.o lib/sys/ifreq.o lib/sys/syscall.o
true
