testdeps =
	lib ../lib/std:std
	lib ../lib/sys:sys
	lib ../lib/crypto:crypto
	lib ../lib/bio:bio
	lib ../lib/testr:testr
;;

bench intsort =
	intsort.myr
;;
bench copious-allocs =
	copious-allocs.myr
;;
bench sha1-compute =
	sha1-compute.myr
;;
bench bigfactorial =
	bigfactorial.myr
;;
bench mandelbrot =
	mandelbrot.myr
;;
bench regex-match =
	regex-match.myr
;;

bench many-memcpy =
	many-memcpy.myr
;;
