</$objtype/mkfile

all:V: _myrrt.$O

_myrrt.$O: _myrrt-plan9.s
	$AS -o _myrrt.$O _myrrt-plan9.s

install:V:
	mkdir -p /$objtype/lib/myr
	cp _myrrt.$O /$objtype/lib/myr

clean:V:
	rm -f _myrrt.$O

nuke:V: clean