testdeps = ../testr:testr ;;

lib crypto =
	# hashes
	hash.myr
	md5.myr
	sha1.myr
	sha256.myr
	sha512.myr
	sha3.myr

	# hmac
	hmac.myr

	# ciphers
	chacha20.myr
	aes.myr

	# randomness
	entropy.myr	# currently assumes a /dev/random
	rand.myr

	lib ../std:std
	lib ../sys:sys
	lib ../thread:thread
;;


lib testutil {noinst} =
	util.myr

	lib ../std:std
	lib ../sys:sys
	lib ../thread:thread
;;

testdeps =
	testutil
	../testr:testr
	../sys:sys
	../iter:iter
	../std:std
;;
